'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    const documentTypes = [
      {
        name: 'Factura de Venta',
        code: 'FAC_VENTA',
        description: 'Factura emitida por venta de bienes o servicios al cliente',
        prefix: 'FV-',
        nextSequence: 1,
        isActive: true,
        fields: JSON.stringify([
          {
            id: 'fv_001',
            name: 'numeroFactura',
            label: 'Número de Factura',
            type: 'text',
            isRequired: true,
            isReadOnly: false,
            order: 1,
          },
          {
            id: 'fv_002',
            name: 'serie',
            label: 'Serie',
            type: 'select',
            isRequired: true,
            options: ['A', 'B', 'C'],
            order: 2,
          },
          {
            id: 'fv_003',
            name: 'moneda',
            label: 'Moneda',
            type: 'select',
            isRequired: true,
            options: ['MXN', 'USD', 'EUR'],
            order: 3,
          },
          {
            id: 'fv_004',
            name: 'metodoPago',
            label: 'Método de Pago',
            type: 'select',
            isRequired: true,
            options: ['Efectivo', 'Transferencia', 'Cheque', 'Tarjeta'],
            order: 4,
          },
          {
            id: 'fv_005',
            name: 'observaciones',
            label: 'Observaciones',
            type: 'textarea',
            isRequired: false,
            order: 5,
          },
        ]),
        createdBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Nota de Crédito',
        code: 'NOT_CREDITO',
        description: 'Documento que reduce la obligación de pago del cliente',
        prefix: 'NC-',
        nextSequence: 1,
        isActive: true,
        fields: JSON.stringify([
          {
            id: 'nc_001',
            name: 'facturaOriginal',
            label: 'Factura Original',
            type: 'text',
            isRequired: true,
            isReadOnly: false,
            order: 1,
          },
          {
            id: 'nc_002',
            name: 'razon',
            label: 'Razón de Crédito',
            type: 'select',
            isRequired: true,
            options: ['Devolución', 'Descuento', 'Error Facturación', 'Daño'],
            order: 2,
          },
          {
            id: 'nc_003',
            name: 'porcentajeDescuento',
            label: 'Porcentaje de Descuento (%)',
            type: 'number',
            isRequired: false,
            order: 3,
          },
          {
            id: 'nc_004',
            name: 'motivo',
            label: 'Motivo Detallado',
            type: 'textarea',
            isRequired: true,
            order: 4,
          },
        ]),
        createdBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Recibo de Pago',
        code: 'REC_PAGO',
        description: 'Constancia de recepción de pago de cliente',
        prefix: 'RP-',
        nextSequence: 1,
        isActive: true,
        fields: JSON.stringify([
          {
            id: 'rp_001',
            name: 'referenciaFactura',
            label: 'Referencia de Factura',
            type: 'text',
            isRequired: true,
            isReadOnly: false,
            order: 1,
          },
          {
            id: 'rp_002',
            name: 'montoRecibido',
            label: 'Monto Recibido',
            type: 'number',
            isRequired: true,
            order: 2,
          },
          {
            id: 'rp_003',
            name: 'metodoPago',
            label: 'Método de Pago',
            type: 'select',
            isRequired: true,
            options: ['Efectivo', 'Transferencia', 'Cheque', 'Tarjeta Crédito', 'Tarjeta Débito'],
            order: 3,
          },
          {
            id: 'rp_004',
            name: 'referenciaTransferencia',
            label: 'Referencia de Transferencia',
            type: 'text',
            isRequired: false,
            order: 4,
          },
          {
            id: 'rp_005',
            name: 'notas',
            label: 'Notas Adicionales',
            type: 'textarea',
            isRequired: false,
            order: 5,
          },
        ]),
        createdBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Nota de Débito',
        code: 'NOT_DEBITO',
        description: 'Documento que aumenta la obligación de pago del cliente',
        prefix: 'ND-',
        nextSequence: 1,
        isActive: true,
        fields: JSON.stringify([
          {
            id: 'nd_001',
            name: 'facturaRelacionada',
            label: 'Factura Relacionada',
            type: 'text',
            isRequired: true,
            isReadOnly: false,
            order: 1,
          },
          {
            id: 'nd_002',
            name: 'concepto',
            label: 'Concepto de Débito',
            type: 'select',
            isRequired: true,
            options: ['Intereses', 'Gastos Administrativos', 'Servicios Adicionales', 'Ajuste de Precio'],
            order: 2,
          },
          {
            id: 'nd_003',
            name: 'monto',
            label: 'Monto a Cobrar',
            type: 'number',
            isRequired: true,
            order: 3,
          },
          {
            id: 'nd_004',
            name: 'descripcion',
            label: 'Descripción',
            type: 'textarea',
            isRequired: true,
            order: 4,
          },
        ]),
        createdBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Guía de Remisión',
        code: 'GUA_REMISION',
        description: 'Documento de comprobante de envío de mercancía',
        prefix: 'GR-',
        nextSequence: 1,
        isActive: true,
        fields: JSON.stringify([
          {
            id: 'gr_001',
            name: 'numeroGuia',
            label: 'Número de Guía',
            type: 'text',
            isRequired: true,
            isReadOnly: false,
            order: 1,
          },
          {
            id: 'gr_002',
            name: 'destinatario',
            label: 'Destinatario',
            type: 'text',
            isRequired: true,
            order: 2,
          },
          {
            id: 'gr_003',
            name: 'direccion',
            label: 'Dirección de Entrega',
            type: 'textarea',
            isRequired: true,
            order: 3,
          },
          {
            id: 'gr_004',
            name: 'peso',
            label: 'Peso (kg)',
            type: 'number',
            isRequired: false,
            order: 4,
          },
          {
            id: 'gr_005',
            name: 'transportista',
            label: 'Transportista',
            type: 'text',
            isRequired: false,
            order: 5,
          },
        ]),
        createdBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    return queryInterface.bulkInsert('document_types', documentTypes, {});
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete('document_types', { code: ['FAC_VENTA', 'NOT_CREDITO', 'REC_PAGO', 'NOT_DEBITO', 'GUA_REMISION'] }, {});
  },
};
